Initial setup for regions
covid-projections/act-now-packages pull request #11
Opened 2022-07-05 20:31 UTC by pnavarrc

2022-07-07 16:41 UTC, pnavarrc commented on packages/regions/tsconfig.json
> +}
Apparently the build command was using the default config (I noticed this because when I tried to build there was an error saying that `get` wasn't enabled with `es5` as a target) - we probably need to add a `tsconfig.json` file on every package

2022-07-07 16:47 UTC, pnavarrc commented on packages/regions/src/datasets/us/County.ts
> +  }
TODO: Use `urlJoin` here (there is some error about `url-join` having 'export')

2022-07-07 16:51 UTC, pnavarrc commented on packages/regions/src/datasets/us/counties_db.ts
> +export default countiesDB;
Not sure if we should export an instance, that might prevent us from marking the package as side-effects free and therefore preventing us from enabling tree shaking.

2022-07-07 16:52 UTC, pnavarrc commented on packages/regions/src/Region.ts
> +  abstract get urlSegment(): string;
TODO: Document the intent for each name, maybe add an example?

2022-07-07 17:03 UTC, pnavarrc commented on packages/regions/src/datasets/us/County.ts
> +  }
This is new, I think it might be useful (and maybe cleaner than checking region types)

2022-07-13 05:50 UTC, mikelehen requested changes
This looks great!  My main high-level feedback is I'd like to see how much functionality we can generalize into the `Region` class so that the rest of our code doesn't need to know about the `State` or `County` classes.  Ideally when we build new sites, we can create new region types as needed (e.g. `City` or `HospitalFacility` or whatever) and it'll be completely transparent to the rest of the code because it will all just deal with the `Region` class directly.

As always, holler if any of the feedback doesn't make sense or you think we should punt on it for now or whatever.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/County.ts
> +  }
Not sure what's going on, but it's tempting to just write our own urlJoin helper. 🤷

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/County.ts
> +  }
It might be a good exercise to figure out why we think we need this (or region types in general).

In a totally ideal world, all of the functionality we need for regions would be baked into the `Region` base class so all of our maps / charts / whatever components would only need to know about `Region` and don't need custom code for counties or cities or census blocks or whatever other regions we come up with in the future.

If we *do* need region types in some form, I think it may be better to have a `RegionType` enum and a `.type` property on `Region`.  That way, like I said, external code doesn't need to be aware of the `County` class at all.  But maybe this is wishful thinking.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/County.ts
> +    public readonly state: State
Could we generalize this and have the `Region` class have a `parent` property?

In a totally ideal world, all of the functionality we need for regions would be baked into the `Region` base class so all of our maps / charts / whatever components would only need to know about `Region` and don't need custom code to deal with `County` and its `state` property, etc.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/Region.ts
> +  abstract get urlSegment(): string;
FWIW- I think it's possible that we could make these all be `public readonly` properties on `Region` instead of using getters, and then instead of having a `County` class, we'd just construct `Region` objects with all of these properties set correctly to represent the counties correctly.

I say that because in an ideal world, none of our code would need to explicitly reference `County` or `State`, etc. All of our maps / charts / components would be powered by `Region` directly and then we wouldn't actually need to have those subclasses if we don't want.  But maybe it's cleaner / more convenient to have the subclasses.  I'm not opposed.  But I do want to try to make the `Region` interface sufficient that the subclasses can just be an implementation detail that the rest of our code doesn't know about.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/Region.ts
> +  // fromJSON
I'd remove these or make them self-explanatory TODOs.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/Region.ts
> +   * with their basic Latin equivalents, replacing whitespaces with lodash
"lodash" => "underscores" ?  lodash is the name of the javascript library.  I guess maybe some people also call underscores a "low dash" or something, but never "lodash" as far as I know. :-)

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/RegionDB.ts
> +    return this.regionsById[regionId] || null;
nit: `?? null` is cleaner / more explicit.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/RegionDB.ts
> +  constructor(public readonly regions: Region[]) {
We have `regions` as a public property but then we also have `all` as a public property as well.  I think we should only have one way to get the list of regions.  Probably `all`?

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/County.ts
> +    return `${this.state.relativeUrl}/county/${this.urlSegment}`;
If we add a `parent` to `Region` then `relativeUrl()` can maybe be implemented inside `Region` by walking up the parent chain.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/Region.ts
> +    public readonly population: number
FWIW- It is tempting to treat population as a metric instead of baking it into the region class.  I'm not sure though, so this is fine for now.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/State.ts
> +    public readonly stateCode: string
Again, I'd question why we need this to be public.  Ideally everything public would be on the `Region` class so that our code doesn't need to know about `State` or other custom region types.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/State.ts
> +  }
I expect we'll need a way to get all counties within a state, right?  E.g. for populating the county map or compare table on a state page.

To do that, I'd like to explore if we can do it in a generic way on the `Region` class, by e.g. having a `children: Region[]` list or something.

Note that we may end up with use cases down the road where a region contains multiple types of other regions (e.g. a state contains both cities and counties).  And we might need to deal with "overlap" in addition to "containment".  E.g. CBSAs overlap with states but aren't strictly contained by a state in some cases.  I'm not sure the best way to represent these sorts of relationships, so probably best to punt for now. But it's something to think about.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/counties_db.test.ts
> +      expect(county).toBeTruthy();
nit: This isn't necessary since the following line would fail if it wasn't truthy.  I'd delete it.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/counties_db.test.ts
> +    expect(() => countiesDB.findByRegionIdStrict("53033")).not.toThrow();
nit: This is redundant since the above two lines didn't throw.  I'd remove it.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/counties_db.ts
> +export default countiesDB;
I'm not sure I follow.  I don't think creating an instance of an object counts as a side-effect.  If we were making a web request, or writing to localstorage, or even modifying some other global state, then it'd be a side-effect.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/index.ts
> +export * from "./State";
Per my other comments, we possibly don't even need to export `County` and `State` if we can make `Region` general enough that the rest of the code doesn't explicitly need to know about `County` and `State`.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/states_db.test.ts
> +      expect(state).toBeTruthy();
nit: This is redundant since the below assert would fail if it weren't truthy, so I'd delete it.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/src/datasets/us/states_db.test.ts
> +    expect(() => statesDB.findByRegionIdStrict("53")).not.toThrow();
nit: This is redundant since the above two lines verify it doesn't throw.

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/tsconfig.json
> +    "rootDir": "src"
Just to be sure, we have to define these compilerOptions here?  We can't put them in the root tsconfig?  Guessing there's an issue with relative directories or something?

2022-07-13 05:50 UTC, mikelehen commented on packages/regions/README.md
> +> Regions
What's our stance on documenting our open source packages?  I think at least eventually it'd be nice if they had some minimal docs.  E.g. a description of what the package is for and a basic usage example.  But we can probably punt on that until things start to stabilize.  But maybe throw a description in here at least?

2022-07-13 18:40 UTC, pnavarrc commented on packages/regions/src/Region.ts
> +    public readonly population: number
We can migrate it once Metric is more stable, that makes sense!

2022-07-13 19:54 UTC, pnavarrc commented on packages/regions/src/datasets/us/County.ts
> +  }
Let's give it a try! Agree that it would be much cleaner if we could have a single `Region` class so location pages and other components don't need to be aware of variants.

2022-07-13 20:29 UTC, pnavarrc commented on packages/regions/README.md
> +> Regions
will do!

2022-07-18 17:37 UTC, smcclure17 approved these changes
Looks great to me as far as I can tell! Just a couple of high-level questions

I assume adding countries would work similarly to adding states/counties? E.g, creating a RegionDB reading from a `countries.json` file, and adding parents to the state regions?

2022-07-18 17:37 UTC, smcclure17 commented on packages/regions/src/Region.ts
> +    public readonly regionId: string,
Just for my understanding, we shouldn't have issues with duplicated/non-unique `regionId`s because different region datasets will use their own `RegionDB` instance (and we expect all the `regionIds` inside a single dataset will be unique)?

E.g., Country ID codes and US Health Service Area codes are both 3-digit numerics, and while these values overlap, it isn't an issue because we expect them to be handled in separate `RegionDB`s?

2022-07-18 17:37 UTC, smcclure17 commented on packages/regions/src/Region.ts
> +    // TODO: transfrom population into a Metric
Again for my understanding, the philosophy here is to add any additional attributes that a region might have as metrics?

2022-07-18 19:55 UTC, pnavarrc commented on packages/regions/src/Region.ts
> +    public readonly regionId: string,
I just added a note to the docs, I hope it's more clear now! I imagine that different projects will use different datasets, and that there could be overlap between the IDs used in the U.S. and IDs used in other countries, so I think it's reasonable to define unique IDs by `RegionID` rather than across all datasets in the package.

2022-07-18 20:17 UTC, merged