Implement OptionSelector component
covid-projections/act-now-packages pull request #130
Opened 2022-09-01 07:01 UTC by pnavarrc

Close #122

2022-09-01 19:52 UTC, mikelehen requested changes
Generally looks good but a few nits and a question about the effect dependencies thing.

> Will punt on that until we can sync with Josh.

Do we have a good way to keep track of things we need Josh to be aware of / weigh in on?  A github/trello board or a running doc or something?  Just feels like we could have friction later if there's a divergence from the mocks and the eng implementations that isn't clearly communicated.

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/components/OptionSelector/OptionSelector.stories.tsx
> +  },
nit: would it make sense to put the onChange handler in the DefaultProps?

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/components/OptionSelector/OptionSelector.tsx
> + * make the component accessible.
Good call, with the accessibility notes!

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/components/OptionSelector/OptionSelector.tsx
> +  const [firstOption] = options;
Feel free to disregard since this is 100% stylistic, but this syntax is less intuitive to me than just `options[0]`.  And since we only use `firstOption` once, I would probably just do `options[0].id` below, which seems pretty straightforward / readable to me.  Up to you though!

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/components/OptionSelector/OptionSelector.tsx
> +  // If the user pass a selectedIOptionId, we update the state to select the
selectedIOptionId => selectedOptionId

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/components/OptionSelector/OptionSelector.tsx
> +  selectedOptionId?: string;
Perhaps rename to `defaultOptionId` since this won't reflect the actual selected option after the user manually clicks on an option, right?  It's only used before the user interacts?

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/components/OptionSelector/OptionSelector.tsx
> +  // https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects
Hrm.  This feels kind of hacky and I'm not sure why we're doing it?  Does it cause a bug if we include `selectedIOptionId` in the effect dependencies?

All else being equal, I think ideally we *should* re-render if `selectedIOptionId` changes, at least if the user hasn't already interacted with the UI (if they have, then it's debatable).

One way to model the state of this component which might help would be:
1. Rename `optionId` to `userSelectedOptionId` and have it be undefined by default. We'll only set it when the user actually clicks on an option.
2. Have this component do something like `const selectedOptionId = userSelectedOptionId ?? defaultOptionId;`

If we do that, then I think we don't need this effect at all?  And the component will automatically update if defaultOptionId changes before the user has selected an option (which might be the behavior we want?  Not sure.).

In general I'm wary of breaking the rules of hooks and skipping dependencies, etc.  I think that will usually result in components that don't behave quite normally.

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/components/OptionSelector/OptionSelector.tsx
> +    });
How is this different / better than:

```
onChange && onChange(event, newOption);
setOptionId(newOption);
```
?

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/components/OptionSelector/OptionSelector.tsx
> +const OptionSelector: React.FC<OptionSelectorProps> = ({
FWIW- This name feels too generic to me.  When I think of "OptionSelector" I think of the `<select>` tag or a dropdown list or something, whereas this component is a more specific visual than that (using toggle buttons).  I am not sure what to call it though.  ToggleOptions? ToggleSelector?   Idunno.  Feel free to leave it as-is if you're not wild about changing the name.

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/styles/theme/components.ts
> +        textTransform: "none",
I feel like border / color / textTransform could probably be moved to "root" and shored with vertical orientation too.

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/styles/theme/components.ts
> +        },
I think this isn't necessary since we're setting border to none already?

2022-09-01 19:52 UTC, mikelehen commented on packages/ui-components/src/styles/theme/components.ts
> +        },
Per my other note, why not just drop the borders entirely for consistency with horizontal?  Don't feel strongly though.  🤷 

![image](https://user-images.githubusercontent.com/206364/188000361-fede1587-3059-411e-ad93-5bf0ea2a0e3e.png)

2022-09-01 19:58 UTC, pnavarrc commented on packages/ui-components/src/components/OptionSelector/OptionSelector.tsx
> +  const [firstOption] = options;
Makes sense 👍

2022-09-01 20:02 UTC, pnavarrc commented on packages/ui-components/src/styles/theme/components.ts
> +        textTransform: "none",
I tried that, but it doesn't really work. The `root` styles apply to the underlying div that represents the `ToggleButtonGroup`; the styles under `grouped`, `groupedHorizontal` and ``groupedVertical` style the `ToggleButton` items under it. Maybe I can consolidate a little but some of the styles need a certain level of specificity.

2022-09-01 20:05 UTC, pnavarrc commented on packages/ui-components/src/styles/theme/components.ts
> +        },
It is necessary because the default styles are set using the `:not(:first-of-type)` pseudo-class, so they have higher specificity than styles set on the default class

2022-09-01 20:06 UTC, pnavarrc commented on packages/ui-components/src/styles/theme/components.ts
> +        },
Maybe! I feel like it will need a 2px border (let's say on the right side) to be visually closer to the horizontal version.

2022-09-01 20:17 UTC, mikelehen commented on packages/ui-components/src/styles/theme/components.ts
> +        textTransform: "none",
Oh, I see.  Yeah, I misunderstood how this works. 😬 

I guess I'd kinda' advocate for duplicating these to the vertical one then, for consistency?  But I don't feel super strongly, especially since we aren't trying to match the vertical mocks or anything.

2022-09-01 20:22 UTC, mikelehen commented on packages/ui-components/src/styles/theme/components.ts
> +        },
Oh, hrm.  I see...  I guess there's a 1px transparent border that we are overriding or something.

How do you figure that sort of thing out?  Is it documented?  Or you're just poking around in dev tools to figure out what you need to override?

2022-09-01 21:31 UTC, pnavarrc commented
Thanks for the review and all the feedback @mikelehen! After giving it some thought, I think that this component might be a bit redundant and that customizing `ToggleButtonGroup` and `ToggleButton` might be enough.

The main use case that I wanted to cover is allowing client code to have an arbitrary option selected by default. This should be easy to do by passing the `defaultOptionId` as prop and using it to set the initial state, but the prop and the internal state can get out of sync (the prop will be ignored to favor the internal state).

One solution is to use the `useEffect(() => setSelectedOption(defaultOptionId), [])` pattern that runs only on mount, which is what I did here. The pattern of using `useEffect(() => {}, [])` to apply the effect only once is fairly well known, but triggers the ESLint rule.

What's making me think that this component might not be worth the trouble is that we need state management on the parent component anyways, because we want to change something else when the user selects an option. For example, if we use it with the US map component, we will have something like this

```tsx
// 
enum LocationType {
  STATES = "states",
  COUNTIES = "counties"
}
const [locationType, setLocationType] = useState(LocationType.STATES);
const options = [
  { id: LocationType.STATES, buttonContent: "States" },
  { id: LocationType.COUNTIES, buttonContent: "Counties" },
];

<OptionSelector
  options={options}
  defaultOptionId={locationType}
  onChange={(e, value) => setLocationType(value)}
/>

<USMap
  metric={metric}
  locationType={locationType}
/>
```

The `OptionSelector` component makes the code a bit more concise, but the parent will still need to have a state, and we need to update the parent state each time that `OptionSelector` changes its internal state. Adding the `defaultOptionId` to the mix makes things a bit more complicated and both states might get out of sync.

Using `ToogleButtonGroup` and `ToggleButton` directly might be more explicit and reduce the chances of making a mistake managing the state, and makes it easier to pass other props to `ToggleButton` without extending the `Option` interface (`disabled`, `color`, etc)

```tsx
<ToggleButtonGroup exclusive value={locationType}  
  onChange={(e, value) => setLocationType(value)}
>
  <ToggleButton value={LocationType.STATES}>States</ToggleButton> 
  <ToggleButton value={LocationType.COUNTIES}>Counties</ToggleButton> 
</ToggleButtonGroup>

<USMap
  metric={metric}
  locationType={locationType}
/>
```

So my proposal is not to remove `OptionSelector` and add stories for `ToggleGroupButton` and `ToggleGroup`. Thoughts? cc @mikelehen

2022-09-01 21:37 UTC, mikelehen commented
@pnavarrc Ah, that's an excellent point!  Yeah, that makes total sense to me.  If we find using ToggleGroup* directly ends up cumbersome / boilerplate-y, we can go back and introduce this component again once it's clear what benefit it will provide.

2022-09-06 00:04 UTC, pnavarrc commented
Removed the OptionSelector component and added stories for MUI's `ToggleButton` and `ToggleButtonGroup` as discussed.

2022-09-07 18:08 UTC, faihegberg approved these changes
![image](https://user-images.githubusercontent.com/46338131/188948216-8f4f9d2e-807d-4041-85c1-5910f20e7689.png)
The size of the text toggle button group seems to change sightly when one toggles it. Not a biggie but it might be good to see if we can keep the size fixed?

2022-09-07 18:08 UTC, faihegberg commented on packages/ui-components/src/styles/theme/components.ts
> +        },
I generally agree with Michael here. I think not having a border on the vertical version looks better (subjective opinion of course). So I don't feel strongly.

2022-09-07 18:10 UTC, pnavarrc commented
The borders between items are removed in the vertical version - going to keep the font-size/weight for now and wait for Josh to be back to confirm / improve on the vertical version. Thanks for the review @faihegberg !

2022-09-07 18:10 UTC, merged