regions: Update RegionDB to take an optional relativeUrl function
covid-projections/act-now-packages pull request #222
Opened 2022-09-26 22:24 UTC by pnavarrc

Part of #220 - Updating the map components to take app regions

First stage is to make `relativeUrl` customizable at the app level. Next will be to have the map components take the regions from the context (and setting up contexts in each project).

2022-09-26 22:25 UTC, pnavarrc commented on packages/regions/src/Region.ts
> +    // TODO: transform population and potentially other attributes to Metric.
Installed a spell checker in VSCode :D

2022-09-27 05:40 UTC, mikelehen requested changes
Not 100% sure I'm on the same page regarding the ultimate plan here.  Feel free to ping me on slack or whatever if that's easier.

2022-09-27 05:40 UTC, mikelehen commented on .changeset/old-lizards-turn.md
> +RegionDB receives options to customize the relativeUrl region
nit: "... to customize the relativeUrls of regions." or something?

2022-09-27 05:40 UTC, mikelehen commented on packages/regions/src/RegionDB.ts
> +  relativeUrl: (region: Region) => string;
I feel like this should be `getRelativeUrl` or `relativeUrlGetter` or something to indicate that it's a function that returns relative URLs?  If you disagree / know of a convention this is following, feel free to push back.

2022-09-27 05:40 UTC, mikelehen commented on packages/regions/src/RegionDB.ts
> +  relativeUrl: () => "",
I almost wonder if this should `fail()` instead.  Is there a case where returning an empty string is helpful?

2022-09-27 05:40 UTC, mikelehen commented on packages/regions/src/RegionDB.ts
> +    // Reconstruct the region array using the provided options
Hrm.  This isn't quite what I was imagining, though it may be another alternative that works.  But it seems like this ends up being equivalent to our existing code where we end up with a RegionDB with "mutated" regions that are different than the regions imported by the map.  So I'm curious what you are imagining for how we actually fix the map.  Would it no longer import states / counties directly somehow?

What I was imagining (I think) was that RegionDB would expose the `relativeUrl()` function as a member, and the map would do something like `regionDb.relativeUrl(region)` to get the URL for a given region.

That way we are never re-creating `Region` instances and the global `RegionDB` used in the app handles "routing" of regions to URLs.  

That said, it does mean we'd need to pass in `regionDB` to the map and any other components that need to generate URLs, which could be cumbersome (unless we put it in a react context?).

Anyway, let me know what you are imagining.  I could likely be convinced this will work out.

2022-09-27 05:45 UTC, mikelehen approved these changes
Actually, based on your slack comments I think you *are* planning to make it so the map is driven by RegionDB and doesn't import states / counties directly.  So if we think we can make that happen, then I think this change is probably fine.

2022-09-27 16:25 UTC, pnavarrc commented
I'm going to close this PR and implement the other solution, thanks for reviewing @mikelehen !

2022-09-27 16:26 UTC, closed without merging