Metric mini map
covid-projections/act-now-packages pull request #313
Opened 2022-10-19 22:40 UTC by faihegberg

Closes https://github.com/covid-projections/act-now-packages/issues/283

Implements a mini map container which accepts a region and a collection of metrics.

![image](https://user-images.githubusercontent.com/46338131/197069628-76afb99e-9486-4887-9f7f-dc905065cca2.png)

![image](https://user-images.githubusercontent.com/46338131/197069467-fe9ab0ed-a308-4f60-89e8-98a86ffbd675.png)

![image](https://user-images.githubusercontent.com/46338131/197069523-4007bd96-0479-44b4-8051-a07e550479ac.png)

![image](https://user-images.githubusercontent.com/46338131/197069573-1fd6dffb-aa16-4aef-ad25-b2ea911ee7d5.png)

**Notes**
- Currently for the single metric display, if you zoom in you'll notice the top right hand corner has a teeny tiny detail where the map appears to be sitting on top of the paper component and is not conforming to the border radius. Not exactly sure how we can enforce the map to conform to the border radius. Let me know if you have any ideas!
- Currently the metric's extended name is left-aligned instead of center-aligned like the mocks. We will need to adjust `MetricLegendThreshold` to explicitly center the text. I held off on this for now as it might affect other components. But I think it would be good to explicitly center it.

2022-10-20 22:08 UTC, faihegberg commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +}
Wonder whether we should establish a more standardized way to get the start and end label. I currently just take the first item in the level set / categories as the lowest and the last item as the highest, which is pretty fragile (i.e. there's no guaranteeing that the first is always the lowest and the last is always the highest).

2022-10-20 22:09 UTC, faihegberg commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +    <Paper sx={{ width: theme.spacing(39) }}>
`theme.spacing(39)` might be a little hard to read. Wonder if we should just stick with pixels here. No strong feelings though!

2022-10-20 22:10 UTC, faihegberg commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +          }}
Pretty minor styling so I didn't separate this into its own style file. Let me know if you think otherwise though!

2022-10-20 23:36 UTC, mikelehen requested changes
Generally looks good but left a few questions / suggestions!

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.stories.tsx
> +  title: "Maps/MetricMiniMap",
Should we move the component files into the components/Maps/ directory to match?

Although @chasulin just reworked the `Maps/` directory in https://github.com/covid-projections/act-now-packages/pull/312 (it's now `USMaps/`).  So maybe we should merge that first?

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +import { MetricUSStateMap } from "../Maps";
Given that `MetricMiniMap` only works with states, it feels like the name should be `MetricUSStateMiniMap` or something.  Though I'm also wondering if we can come up with a better differentiator than just "mini"...  I'm not sure though, so maybe just stick with "mini" for now.

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.stories.tsx
> +};
Is there a reason we wouldn't want to just make this the builtin tooltip behavior so you don't have to provide a `renderTooltip` handler?  Would make the component easier to use.

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +    const levels = metric.levelSet.levels;
Note that I reworked levels in #319 and so once that lands this will end up being `categorySet` and `categorySet.categories` and you won't need two separate cases for levels vs categories.

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +}
I feel like this startLabel / endLabel stuff should be built into `MetricLegendThreshold`. Or at least it should have a default implementation that does this.  Can you open a github issue for us to consider doing that?

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +  } else return "Low";
I feel like this should be an error, e.g.:

```
fail(`Metric must have categories to be used with MetricMiniMap. ${metric} does not.`);
```

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +  } else return "High";
ditto

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +export const MetricMiniMap: React.FC<MetricMiniMapProps> = ({
Can you add a doc comment explaining what this component is?

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +    <Paper sx={{ width: theme.spacing(39) }}>
Hrm, yeah. I assumed we only use spacing() for spacing between components, etc.  For specifying the actual size of a component, we'd use pixels.  But I'm not sure.

That said, in general it's not obvious to me that this component should have a fixed size (rather than letting the consumer of the component control the size).  So maybe it should accept width/height props?  But I'm not really sure how we expect layout stuff like this to work.   Maybe @pnavarrc can weigh in on how he'd imagine this working.

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +              <Typography>{metricCatalog.getMetric(metric).name}</Typography>
Rather than doing `metricCatalog.getMetric(metric)` over and over (I see 5 I think), I'd suggest doing:

```
const resolvedMetrics = metrics.map(m => metricCatalog.getMetric(m));
```
at the top and then using `resolvedMetrics.map(metric => ...)` down here so they're guaranteed to be `Metric` objects...

2022-10-20 23:36 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +          width={160}
using pixels here but spacing() above seems inconsistent.

2022-10-20 23:44 UTC, pnavarrc commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +    <Paper sx={{ width: theme.spacing(39) }}>
Yeah, theme spacing shouldn't be used for component widths. In this case, I would recommend adding an optional `width` prop to the component to match `USStateMap` (we can grab the default width from it too)

2022-10-20 23:48 UTC, pnavarrc commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +          width={160}
yeah, consider using AutoWidth or just the `width` prop (once added)

2022-10-20 23:48 UTC, pnavarrc commented on packages/ui-components/src/index.ts
> +export * from "./components/MetricMiniMap";
Maybe put this in order once the component is renamed?

2022-10-24 19:18 UTC, chasulin commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.stories.tsx
> +  title: "Maps/MetricMiniMap",
i renamed the files/folder to `MetricUSMiniMap`, to express that its a US map (and we could eventually have non-US versions of this down the road.. although they could probably be unified into a single minimap component, but we can cross that bridge/rename when/if it comes to it?)

and, i kept it in its own directory (`MetricUSMiniMap`), separate of the `USMaps` and `MetricUSMaps` directories, because those are for the base map components, and this is a more specific thing composed of multiple components (legend, map, dropdown menu, etc.)

the file structuring can get a little head-y, so im not very tied to any of this^^. if something else makes more sense to anyone reading this, please feel free to chime in 😎

2022-10-24 19:22 UTC, chasulin commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.stories.tsx
> +};
hm, nixing `renderTooltip` prop would nix the ability to customize the tooltip beyond just displaying the region name. im not opposed, but might be limiting down the line. we can make `renderTooltip` optional and set this^ as the default for now

2022-10-24 19:25 UTC, chasulin commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +import { MetricUSStateMap } from "../Maps";
ah yes, see [here](https://github.com/covid-projections/act-now-packages/pull/313/files#r1003665440)

re: "mini", im getting rid of the built-in width, so now it can be flexible/any size/dependent on a parent container. i think we're outgrowing the term "mini" ..

2022-10-24 19:28 UTC, chasulin commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +    <Paper sx={{ width: theme.spacing(39) }}>
setting the width to depend on whatever wraps the component to keep things flexible

2022-10-24 19:33 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +import { MetricUSStateMap } from "../Maps";
Maybe we should have some term for components that are standalone widgets ready to be dropped into the homepage / location page.  E.g. `MetricUSStateMapWidget` or `MetricUSStateMapBlock` or something?  Idunno.

2022-10-24 19:33 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.stories.tsx
> +};
Sounds good!

2022-10-24 19:34 UTC, mikelehen commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.stories.tsx
> +  title: "Maps/MetricMiniMap",
Sounds reasonable!

2022-10-24 20:43 UTC, chasulin commented on packages/ui-components/src/components/MetricMiniMap/MetricMiniMap.tsx
> +}
added it to the queue [here](https://github.com/orgs/covid-projections/projects/6/views/1)

2022-10-25 19:52 UTC, chasulin commented on packages/ui-components/src/components/MetricUSMiniMap/MetricUSMiniMap.style.tsx
> +`;
put these into a style file because it was a bit crowded to write the second set of styles inline

2022-10-25 21:43 UTC, mikelehen commented
Still reviewing, but I'm seeing issues with the thermometer width on some screen sizes (e.g. "Small Mobile" in Storybook):
![image](https://user-images.githubusercontent.com/206364/197887779-cc978bc7-45fb-485b-ade2-9d8207c1a1a8.png)

2022-10-25 22:11 UTC, chasulin commented
> Still reviewing, but I'm seeing issues with the thermometer width on some screen sizes (e.g. "Small Mobile" in Storybook): ![image](https://user-images.githubusercontent.com/206364/197887779-cc978bc7-45fb-485b-ade2-9d8207c1a1a8.png)

yeah im adding a github issue to work on the responsiveness of the legend/therm. lets ignore the responsiveness that component for the purpose of this pr for now

2022-10-26 00:14 UTC, mikelehen approved these changes
Few small suggestions, but looks great. Thanks for getting this over the finish line.

2022-10-26 00:14 UTC, mikelehen commented on packages/ui-components/src/components/MetricUSMaps/MetricUSNationalMap/MetricUSNationalMap.tsx
> +          : "#eee";
FWIW- If you merge `develop` in we should be able to revert this change here and in `MetricUSStateMap.tsx` below.  I did this as a temporary fix, but the real fix is in now.

2022-10-26 00:14 UTC, mikelehen commented on packages/ui-components/src/components/MultiMetricUSStateMap/MultiMetricUSStateMap.tsx
> +  /** All regions to include on the map */
This could be a bit confusing (we aren't going to include all the regions in the region db on the map).  Perhaps just say "Region DB instance (used for generating region links, etc.)." or similar.

2022-10-26 00:14 UTC, mikelehen commented on packages/ui-components/src/components/MultiMetricUSStateMap/MultiMetricUSStateMap.tsx
> +  /** Region corresponding to the page on which the component is being rendered */
This makes some assumptions about how this component is being used.  I think I would just say "An optional region to highlight on the map." or something.  As an aside, I think "selectedRegion" would be a bit clearer name, but then we'd need to update the other map components as well.

2022-10-26 00:14 UTC, mikelehen commented on packages/ui-components/src/components/MultiMetricUSStateMap/MultiMetricUSStateMap.tsx
> +  renderTooltip: (regionId: string) => React.ReactElement | string;
I think we want this to be optional, so it should be `renderTooltip?: ...` ?

also nit: Maybe use `React.ReactNode` which includes `string` already?  Or is that too permissive for some reason?

2022-10-26 00:14 UTC, mikelehen commented on packages/ui-components/src/components/MultiMetricUSStateMap/utils.ts
> +// TODO (Chelsi) - move these to MetricLegendThreshold (or somewhere more central than here)
You could do "TODO(#325)" to reference the github issue...

2022-10-26 15:31 UTC, chasulin commented on packages/ui-components/src/components/MultiMetricUSStateMap/MultiMetricUSStateMap.tsx
> +  /** Region corresponding to the page on which the component is being rendered */
good call

2022-10-26 18:55 UTC, merged