Accommodate negative values in charts
covid-projections/act-now-packages pull request #388
Opened 2022-11-09 20:08 UTC by faihegberg

2022-11-14 23:24 UTC, faihegberg commented on packages/ui-components/src/stories/mockData.ts
> +);
Convert to degrees celsius just so we can see more negative values in our mocks.

2022-11-15 01:16 UTC, pnavarrc requested changes
Added some suggestions!

2022-11-15 01:16 UTC, pnavarrc commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> +            }
Since the intervals are provided as prop, we shouldn't count on them to be sorted in a specific way. For example, this wouldn't work if the intervals are passed in reverse order.

Maybe find the interval that has the lower `y` starting point instead?

2022-11-15 01:16 UTC, pnavarrc commented on packages/ui-components/src/components/MetricLineThresholdChart/MetricLineThresholdChart.tsx
> +            tickValues: [0].concat(thresholds),
I don't think we should force `0` to be part of the tick values (it can always be added to the thresholds if the value is relevant for a particular metric

2022-11-15 01:16 UTC, pnavarrc commented on packages/ui-components/src/components/MetricLineThresholdChart/MetricLineThresholdChart.tsx
> +    domain: [minChartValue, maxChartValue * 1.1],
I don't think we need to change the `yScale` domain to avoid cropping the intervals (I changed this in the PR and all the stories look the same)

2022-11-15 01:16 UTC, pnavarrc commented on packages/ui-components/src/stories/mockData.ts
> +  })
Maybe write a function to convert from Fahrenheit to Celsius to improve readability (even if we only use it once).

Consider fully spelling the name (e.g. `newYorkTemperature`) to improve readability

2022-11-15 01:16 UTC, pnavarrc commented on packages/ui-components/src/stories/mockData.ts
> +export const NYCtempTimeseries = new Timeseries(NYCtemp);
Same with the timeseries!

2022-11-15 01:16 UTC, pnavarrc commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> +                ? Math.min(yFrom, yTo) - 5
Maybe name the `5` for readability? it could also be an optional parameter of the chart (`firstIntervalOffset` or something)

2022-11-15 01:16 UTC, pnavarrc commented on packages/ui-components/src/components/Axis/Axis.style.tsx
> +    hideZero={false}
I don't think we should change this

2022-11-15 01:16 UTC, pnavarrc commented on packages/ui-components/src/components/MetricLineThresholdChart/MetricLineThresholdChart.stories.tsx
> +  metric: MetricId.NYC_TEMP,
Consider fully spell the name `NYC_TEMPERATURE` for clarity

2022-11-15 01:16 UTC, pnavarrc commented on packages/ui-components/src/stories/NYCtempDataProvider.ts
> +export class NYCtempDataProvider extends SimpleMetricDataProviderBase {
Not to increase scope too much, but maybe we could return the temperature data for other cities/states if we have them? That way we can use this provider with multiple states  to test Trends, for example

2022-11-15 01:24 UTC, mikelehen commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> +                ? Math.min(yFrom, yTo) - 5
What is this 5 for, exactly?  Padding on the bottom of the chart?  But we did padding on the top of the chart via a 1.1 multiplier in MetricLineChart, right?  Is there a way to make the padding work the same way?

2022-11-15 01:26 UTC, mikelehen commented on packages/ui-components/src/components/MetricLineThresholdChart/MetricLineThresholdChart.tsx
> +            tickValues: [0].concat(thresholds),
I was telling Fai that these charts without a labeled 0 value look weird to me:
![image](https://user-images.githubusercontent.com/206364/201803736-f88d8a24-a107-4f51-9367-91e152b86a4c.png)

But I guess that's how CAN works and it's never been an issue.  I was thinking maybe if a chart has min/max values then we should put those on the axis labels, but not 100% sure.  Anyway, I'm fine with punting on this labeling for now.

2022-11-15 19:12 UTC, faihegberg commented on packages/ui-components/src/components/MetricLineThresholdChart/MetricLineThresholdChart.tsx
> +            tickValues: [0].concat(thresholds),
I agree with Michael here, but I don't feel strongly. I added it not only because I think it's intuitive to see a zero on the chart, but putting it into the threshold would mean that zero is explicitly an upperbound of one level and a lowerbound of the next level, which is not necessarily true for the metric we're defining.

I'll leave out the zero for now and if there's a clarity issue in the future, we can always add it.

2022-11-15 19:14 UTC, faihegberg commented on packages/ui-components/src/stories/NYCtempDataProvider.ts
> +export class NYCtempDataProvider extends SimpleMetricDataProviderBase {
Sounds great! I'll do this in a follow-up PR.

2022-11-15 19:24 UTC, faihegberg commented on packages/ui-components/src/stories/mockData.ts
> +export const NYCtempTimeseries = new Timeseries(NYCtemp);
I assume you're referring to the renaming.

2022-11-15 20:23 UTC, faihegberg commented on packages/ui-components/src/components/MetricLineThresholdChart/MetricLineThresholdChart.tsx
> +    domain: [minChartValue, maxChartValue * 1.1],
You're right that we don't need this to avoid cropping the intervals, but this does provide the extra vertical padding at the top of the chart. So the highest point of the line is not at the same vertical position as the top of the y-axis. Without this 10% padding (with the cropped line issue now fixed) it would look like:
![image](https://user-images.githubusercontent.com/46338131/202016646-2f648c76-036c-4b87-b396-b3c108234374.png)

vs. with the 10% padding it would look like:
![image](https://user-images.githubusercontent.com/46338131/202017473-a584e638-6419-4ba2-954a-4cb64ec2a53c.png)

Personally I think the latter option looks better, but I don't feel strongly, since there are probably other, more elegant ways to add white space. So I'll remove it for now, given that the cropped line issue is the prioritized fix and that is already achieved.

2022-11-15 20:40 UTC, faihegberg commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> +                ? Math.min(yFrom, yTo) - 5
@pnavarrc I renamed the 5 and made it an optional variable 🙂 

@mikelehen The 5 is variable that determines the amount of padding _just at the top interval_ of the chart. This is the key ingredient that resolves the line getting cropped issue, as it adjusts the `RectClipGroup` of only the top interval. In contrast, the 1.1 multiplier in the `MetricLineChart` expands the domain of the yScale by increasing its upperbound. This forces the y-axis to extend longer at the top. So although both of these introduce white space, they do so in different ways. That said, I just got rid of this 1.1 multiplier ([see this comment](https://github.com/covid-projections/act-now-packages/pull/388#discussion_r1023225213)). I can also explain on a call if you want 🙂

2022-11-15 21:01 UTC, pnavarrc commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> +  const topPoint = Math.max(...intervals.map((interval) => interval.upper));
This won't work because if the yScale is reversed, then the top most interval will be the one that has lower `upper` and `lower` values. For example, with:

```tsx
const yScale = scaleLinear({
  domain: [0, 1000],
  range: [0, 100]
})
```

will cause `topPoint` will be the interval at the bottom of the chart, which is not what we want.

Also, `upper` could end up at the bottom of the interval (again, depending on the scale), so we will need to compare both the `upper` and the `lower` ends of the interval (that's why we use `Math.min(yFrom, yTo)` instead of just `yFrom` or `yTo`

2022-11-15 21:40 UTC, faihegberg commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> +  const topPoint = Math.max(...intervals.map((interval) => interval.upper));
Good point 😅

2022-11-16 20:38 UTC, mikelehen approved these changes
A few nits, but overall looks good!

2022-11-16 20:38 UTC, mikelehen commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> +  /** Optional offset on the y-axis to pad the highest point on the chart */
This is a pixel offset, right?  Can you say "Optional offset (in pixels)" to make that clear? Also, maybe add `@default 5` per Chelsi's note at standup.

2022-11-16 20:38 UTC, mikelehen commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> + * won't be rendered. The chart will also have a padding of 5 at the top.
I'd remove this and let the `topIntervalOffset` documentation communicate this.

2022-11-16 20:38 UTC, mikelehen commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> + * @param topIntervalOffset Optional offset on the y-axis to pad the highest point on the chart.
I don't think we need / want all of these `@param`s here.  They seem redundant and don't show up in the generated docs: https://act-now-packages.web.app/docs/functions/ui_components_src.LineIntervalChart.html

If in doubt, maybe double-check with @chasulin since she's auditing prop docs right now.

2022-11-16 20:38 UTC, mikelehen commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> +            }
Rather than duplicate this logic twice (which makes it a bit harder to read and risks them getting out-of-sync, etc.), how about add this above:

```
const topOffset = (topIntervalOffset && Math.min(yFrom, yTo) === topPoint) ? topIntervalOffset : 0;
```

And then you can just do `y={Math.min(yFrom, yTo) - topIntervalOffset}` and `height={clipHeight + topIntervalOffset}`

2022-11-16 20:38 UTC, mikelehen commented on packages/ui-components/src/stories/NYCtempDataProvider.ts
> + * ranges of values.
I don't really understand how this description relates to what this data provider actually does or is for.  Shouldn't it say "Data provider that provides NYC temperature data for all regions. " or something?  And maybe include a TODO about making it include real data for other cities if we plan to do that in the future. 🤷 

FWIW- I'm also not 100% sure why we need this provider.  We could use the existing MockDataProvider with a negative `minValue` if all we want is timeseries data that includes negative numbers.  

That said, it doesn't seem like a bad idea to have some more realistic data available for testing, so I'm not opposed to adding temperature data for storybook testing purposes if we want to. 🤷

2022-11-16 20:38 UTC, mikelehen commented on packages/ui-components/src/stories/NYCtempDataProvider.ts
> +export class NYCtempDataProvider extends SimpleMetricDataProviderBase {
nit: I think this should be `NycTempDataProvider` to match our convention with e.g. CsvDataProvider...  or are we inconsistent on that?

Also I'd spell out temperature, since "temp" is somewhat ambiguous (temp => temporary)

2022-11-16 20:38 UTC, mikelehen commented on packages/ui-components/src/stories/mockData.ts
> +const NYCtemperature = cityTemperature.map(
Similarly, this should perhaps be nycTemperature?

2022-11-16 20:38 UTC, mikelehen commented on packages/ui-components/src/stories/mockData.ts
> +export const NYCtemperatureTimeseries = new Timeseries(NYCtemperature);
And nycTemperatureTimeseries?

2022-11-17 00:35 UTC, faihegberg commented on packages/ui-components/src/components/LineIntervalChart/LineIntervalChart.tsx
> + * @param topIntervalOffset Optional offset on the y-axis to pad the highest point on the chart.
I wonder whether this is because it's an optional prop, but I'll remove it.

2022-11-17 00:45 UTC, faihegberg commented on packages/ui-components/src/stories/NYCtempDataProvider.ts
> + * ranges of values.
Whoops, yes, this comment is supposed to be updated. I'll revise it. I think it's beneficial to have some variety of realistic data for us to test so I'll keep it. I'll also make sure this provider provides temperature for other cities too as a follow-up PR.

2022-11-17 01:18 UTC, merged