Add legend threshold vertical
covid-projections/act-now-packages pull request #46
Opened 2022-08-09 22:46 UTC by faihegberg

WIP! This PR adds legend threshold vertical to Act Now Packages.

2022-08-10 21:11 UTC, pnavarrc commented on packages/ui-components/src/components/LegendThreshold/LegendThresholdHorizontal.tsx
> + * `LegendThreshold` represents a scale with thresholds that separate
Consider updating the docstring (LegendThresholdHorizontal)

2022-08-10 21:21 UTC, pnavarrc requested changes
I think it will be best if we create different props for vertical and horizontal (hopefully they will converge eventually), since `barHeight` and `showLabels` are not relevant for the vertical variant. I added a suggestion on how to go about it

2022-08-10 21:21 UTC, pnavarrc commented on packages/ui-components/src/components/LegendThreshold/LegendThresholdHorizontal.tsx
> +}: LegendThresholdProps<T> &
I think we can simplify a little here. The vertical and horizontal versions don't have exactly the same props, so maybe we can do something like this

```tsx
// interfaces.ts
export interface CommonLegendThresholdProps {
  width: number;
  height: number;
  // etc...
}

// LegendThresholdHorizontal.tsx
interface LegendThresholdHorizontalProps extends CommonLegendThresholdProps {
  orientation: 'horizontal';
  barHeight?: number;
  showLabels?: boolean;
  // ...etc
}

// LegendThresholdVertical.tsx
interface LegendThresholdVerticalProps extend CommonLegendThresholdProps {
  orientation: 'vertical';
  // ...etc
}
```

and then

```tsx
type LegendThresholdProps = LegendThresholdHorizontalProps | LegendThresholdVerticalProps;

const LegendThreshold: React.FC<LegendThresholdProps> = (props) => {
  return props.orientation === 'horizontal
    ? <LegendThresholdHorizontal {...props} />
    : <LegendThresholdVertical {...props} />;
}
```

2022-08-11 17:10 UTC, chasulin reviewed
i wonder if we should use the material-ui-ish way of setting props using booleans where possible, rather than 'vertical' vs 'horizontal'. [in LegendCategorical, i just defaulted to horizontal (an optional horizontal prop that defaults to true)](https://github.com/covid-projections/act-now-packages/blob/develop/packages/ui-components/src/components/LegendCategorical/LegendCategorical.tsx#L17) -- i can definitely change legend categorical to match the types you use here. totally up for either way, but we should try to be consistent with conventions like this

and per the point on omitting labels for now, i feel like we can add them with the assumption that they should have some sort of max-width and wrapping behavior. the specifics of the width can change in the future if need be, but its probably a safe assumption to make and start on?

2022-08-11 21:04 UTC, faihegberg commented on packages/ui-components/src/components/LegendThreshold/LegendThresholdVertical.tsx
> + */
Keeping this comment here as labels will be implemented in a follow-up PR.

2022-08-11 21:48 UTC, faihegberg commented on packages/ui-components/src/components/LegendThreshold/LegendThresholdVertical.tsx
> +  getItemEndLabel?: (item: T, itemIndex: number) => string;
This will be adjusted as a follow-up PR.

2022-08-15 17:04 UTC, pnavarrc commented on packages/ui-components/src/components/LegendThreshold/LegendThreshold.tsx
> +) => {
Why are we omitting the props of `LegendThrehsoldHorizontal`? I think it should just be 

```tsx
const LegendThreshold = <T,>(props: LegendThresholdProps<T>) => {
  /* ...*/
}
```

2022-08-15 17:09 UTC, pnavarrc requested changes
Added some comments, types need to be adjusted

2022-08-15 17:09 UTC, pnavarrc commented on packages/ui-components/src/components/LegendThreshold/LegendThresholdVertical.tsx
> +  getItemEndLabel?: (item: T, itemIndex: number) => string;
Why do we have end labels? For the vertical legend, the props will likely be different (each level will have an interval, see the mocks)

2022-08-15 17:09 UTC, pnavarrc commented on packages/ui-components/src/components/LegendThreshold/interfaces.ts
> +  orientation?: "horizontal" | "vertical";
This is not a common prop (the legend threshold vertical should only receive "vertical")

2022-08-15 17:09 UTC, pnavarrc commented on packages/ui-components/src/components/LegendThreshold/LegendThresholdHorizontal.tsx
> +}
Consider adding `orientation="horizontal"` here and the equivalent for the vertical

2022-08-15 18:18 UTC, faihegberg commented on packages/ui-components/src/components/LegendThreshold/LegendThresholdVertical.tsx
> +  getItemEndLabel?: (item: T, itemIndex: number) => string;
Adjusting to `getItemLabel` and `getItemSublabel`.

2022-08-15 18:55 UTC, pnavarrc approved these changes
Looks good!

2022-08-15 20:02 UTC, merged