JSON records provider
covid-projections/act-now-packages pull request #465
Opened 2022-11-30 20:18 UTC by smcclure17

2022-11-30 21:24 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> -  private async populateCache(): Promise<void> {
I'm not sure how important it is to have some of these methods be private (though it's definitely preferred). Using an abstract base class makes that impossible as far as I'm aware 😕

2022-11-30 21:24 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> -  async fetchDataForRegionAndMetric(
I've moved this to an abstract base class `DataRowMetricProviderBase` (naming?) as this would have been copied over 1:1 to the JSON provider

2022-12-01 19:57 UTC, mikelehen requested changes
This looks good but I have a couple semi-disruptive comments (about inheritance and fixing a preexisting caching issue with the CSV data provider). Sorry!

2022-12-01 19:57 UTC, mikelehen commented on packages/metrics/src/data_providers/DataRowMetricProviderBase.ts
> +   * Required if the JSON file contains timeseries data, else it should not be specified.
This says JSON but it's meant to be shared between CSV and JSON, right?

TBH I think I would maybe make `CsvDataProviderOptions` and `JsonDataProviderOptions` *not* extend this interface and be 100% standalone.  That will:
1. Let us name / document the options in a way that is maximally user-friendly (refer to CSV columns for CSV and JSON fields for JSON or whatever).
2. Result in simpler auto-generated documentation, I think (the user can go to one page and see all the options rather than having to look at the base options separately).

2022-12-01 19:57 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> -  private async populateCache(): Promise<void> {
I think you can mark it `protected`, though see my other comment about using inheritance.

2022-12-01 19:57 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> -  async fetchDataForRegionAndMetric(
Would it be possible to use a shared helper function or class instead?  In general, while inheritance can be a very useful tool in some cases, it can also make the code harder to read, especially if the parent class is basically a collection of useful code as opposed to a well-defined class that can be easily described / reasoned about on its own. The fact that there isn't an obvious name for the parent class suggests this is more of the former case. 

Using explicit helper functions / classes can often be a simpler solution.

Alternatively, I would actually say this is a small enough chunk of code that repeating it once wouldn't be the end of the world.  I think we can actually drop the `metricData.dropTimeseries()` call.  I added code to MetricCatalog to do that automatically for all providers.

2022-12-01 19:57 UTC, mikelehen commented on packages/metrics/src/data_providers/DataRowMetricProviderBase.ts
> +      await this.populateCache();
Sorry for not bringing this up before you started on this PR, but there's actually an issue with the CSV data provider where it will parse the CSV file repeatedly while we're waiting for the network fetch to complete. https://github.com/covid-projections/act-now-packages/issues/454 This is 100% my fault. I fixed it to not repeat the network fetches a while ago, but did it in a naive way that didn't prevent us from re-parsing the CSV content. 🤦 

Especially if we're going to be sharing code, it might make sense to tackle #454 first so that we don't repeat the same mistake in the JSON provider.

2022-12-05 19:08 UTC, smcclure17 commented on packages/metrics/src/data_providers/DataRowMetricProviderBase.ts
> +      await this.populateCache();
Np! In 89f6f3158d7ffeb0af13e834df338e227bb230bb I've reworked it to a similar structure to how the CSV fetching promises are handled, which does mean that I slightly changed the way the cache gets populated. LMK if this doesn't feel like a clean/good solution and I can put some more thought into it

2022-12-05 19:10 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> -  async fetchDataForRegionAndMetric(
Yeah, that reasoning makes sense! I've restructured this to a shared util function in `data_provider_utils.ts`

Thanks!

2022-12-05 19:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
>        // the existing promise.
I think this comment is kinda' wrong / misleading now (we're no longer at risk of hitting this code when we're already fetching the CSV) and also we don't need the `fetchedText` promise anymore. I think we could remove it and change the constructor to populate `this.dataRowsByRegionId` in the case that you pass in test csv data to use.

2022-12-05 19:36 UTC, smcclure17 commented on packages/metrics/package.json
> +    "encoding": "^0.1.13",
When testing in https://github.com/covid-projections/fai-hackathon-nov-2022/pull/23 I was getting an error of something like `module encoding not found`. Adding it here fixed it, but I'm unsure if this should be necessary?

2022-12-05 19:40 UTC, mikelehen commented on packages/metrics/package.json
> +    "encoding": "^0.1.13",
Hrm.  Strange.  Any idea what triggered it?  It doesn't seem like we are actually accessing any functionality from it.  It's possible that some module requires this as a peer dependency or something, except you're not adding any new new modules in this PR, so I'm confused.  To be clear was this error related to this PR in any way?

2022-12-05 20:16 UTC, smcclure17 commented on packages/metrics/package.json
> +    "encoding": "^0.1.13",
Not entirely sure what causes it atm 😕, but it does seem to be specific to this PR. Running the template on the published `metrics` package doesn't result in the same issue.

FWIW, this is the error I get without adding the `encoding` dependency:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/55333380/205733016-05a48a97-f3c6-455c-95f3-77ac7b557a22.png">

2022-12-05 20:18 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.ts
>        // the existing promise.
Ah, yeah true--updated this in 74397fd2b9f11939baee1056078ffe6f074c5313

2022-12-05 20:31 UTC, mikelehen reviewed
Basically looks good but I want to look at the `encoding` dependency before approving.  I'm confused.

2022-12-05 20:31 UTC, mikelehen commented on packages/metrics/src/data_providers/JsonDataProvider.test.ts
> + * @param dateCol Name of date column.
Missing documentation for `metric`

2022-12-05 20:31 UTC, mikelehen commented on packages/metrics/src/data_providers/JsonDataProvider.test.ts
> +const jsonTimeseries = [
nit: `mockJson` and `jsonTimeseries` are used similarly but one is labeled as `mock` and one is not.  I'd probably drop "mock" entirely and use "test" in both (similar to `testMetric`), but don't feel strongly.

2022-12-05 20:31 UTC, mikelehen commented on packages/metrics/src/data_providers/JsonDataProvider.ts
> +  dateColumn?: string;
nit: Does it make sense to use "column" when referring to JSON data?  I think I'd expect "property" or "field", but could be convinced otherwise if we think there's value in making the providers use similar terminology. 🤷

2022-12-05 20:31 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +  const metricKey = metric.dataReference?.column;
nit: Here again I would expect to use `field` or `property` for JSON data.  So consider passing `metricKey` in instead of `metric`.  That said, again, if you feel like there's value in keeping this uniform between using CSV and JSON data, I could be talked into that.

2022-12-05 20:31 UTC, mikelehen commented on packages/metrics/src/data_providers/JsonDataProvider.test.ts
> +        /*datColumn=*/ "date",
dateColumn

2022-12-05 20:31 UTC, mikelehen commented on packages/metrics/src/data_providers/JsonDataProvider.ts
> +   * Required if the CSV contains timeseries data, else it should not be specified.
CSV => JSON

2022-12-05 20:31 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +export function groupAndValidateRegionIds(
Nice helper function! I'd maybe tweak the name to `groupAndValidateRowsByRegionId`

2022-12-05 20:31 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +) {
Can you add the return type for readability?

2022-12-05 20:31 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
>      );
Is this assert redundant with the above if-check now?  Will TypeScript let us remove it?

2022-12-05 21:03 UTC, mikelehen approved these changes

2022-12-05 21:03 UTC, mikelehen commented on packages/metrics/package.json
> +    "encoding": "^0.1.13",
So I'm seeing a warning in the console when I build act-now-packages from `develop` and `yarn link` that into fai-hackathon-2022, so I think maybe this is related to `yarn link` but not your specific changes.

```
warn  - ../act-now-packages/packages/metrics/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/mikelehen/src/act-now-packages/packages/metrics/node_modules/node-fetch/lib'
```

Based on what I'm seeing, node-fetch has an optional peer dependency on the encoding module: https://github.com/node-fetch/node-fetch/blob/1ef4b560a17e644a02a3bfdea7631ffeee578b35/package.json#L47

So it will use it if it's there, but it shouldn't fail when it's not there.

My suspicion is that this is a bug / quirk with `yarn link` and if you just merge your changes without adding `encoding` as a dependency and publish the packages, the published packages will work fine.  That said, if that means `yarn link` won't work for us going forward, maybe we should just explicitly add `encoding` even though we don't need it.  I don't really like bloating our dependencies needlessly though, so I'm kinda' on the fence.  Will leave it up to you!

As an aside, the latest versions of node-fetch don't [seem](https://github.com/node-fetch/node-fetch/blob/main/package.json) to have the `encoding` peer dependency, but last I checked we couldn't use the latest version because it only supports EcmaScript style imports, not CommonJS, which doesn't work with our next.js config, so upgrading probably isn't an option. :-/

2022-12-05 21:08 UTC, smcclure17 commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +  const metricKey = metric.dataReference?.column;
Yeah, this makes sense/I agree we should use format-specific language 

I've renamed the affected fields and moved this logic as you've suggested 🙏

2022-12-05 21:14 UTC, smcclure17 commented on packages/metrics/package.json
> +    "encoding": "^0.1.13",
Ahh, interesting 🤔 thanks for digging into this! 🙏 

I agree with not adding dependencies unless strictly necessary, so let's try this without adding the encoding dependency, then later if we feel like it's necessary/helpful we can reconsider if need be. 

Thanks again for looking into this

2022-12-05 21:18 UTC, merged