WIP: Prototype CSV data-provider
covid-projections/act-now-packages pull request #61
Opened 2022-08-15 17:53 UTC by smcclure17

2022-08-15 22:20 UTC, smcclure17 commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +export function dataRowsToMetricData(
Ideally this function could be reused by other data providers that read data in row/record format (like a JSON  provider)

2022-08-15 22:20 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +    if (!includeTimeseries && metricData.hasTimeseries()) {
It seems like the `includeTimeseries` arg in `getDataFromCache()` should always match the arg in`populateCache()` (as is the case in `fetchData()`), so we maybe shouldn't have to specify whether we want timeseries data or not, but I've added this in case the args aren't equal.

2022-08-15 22:20 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +    expect(
The line splitting makes these a little hard to parse I think, so I'm willing to refactor these in the name of clarity if we'd like

2022-08-15 22:26 UTC, smcclure17 commented on packages/metrics/src/data/MetricData.ts
> +  dropTimeseries(): MetricData {
Maybe this should just be a setter like
```typescript
  dropTimeseries(): void {
    this._timeseries = undefined
  }
```
but I felt there was safety in returning a new object

2022-08-16 19:38 UTC, mikelehen commented on packages/metrics/src/data/MetricData.ts
> +  dropTimeseries(): MetricData {
💯

I'm a big fan of immutable objects where there is no way to modify them directly.  Instead, any "mutator" functions just create & return a new instance that is independent from the original one.  In general, immutable objects / values make code much easier to understand / reason about (mutability leads to a lot of difficult-to-diagnose bugs).  TBH this is probably the biggest lesson in programming that I've learned since getting my CS degree. 😁

2022-08-16 22:36 UTC, mikelehen requested changes
I left a lot of feedback (sorry!) but overall this is looking good.  Holler if anything doesn't make sense or you want to punt on some of the items or whatever.  Thanks!

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data/MetricData.ts
> +  dropTimeseries(): MetricData<T> {
Can you add a doc comment?  I'm trying to be pretty exhaustive with documenting classes and their public methods / properties.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +      console.log(payload[0].cool_metric);
Remove console.log?

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +    expect(
Yeah, that sounds good to me.  I almost always break up expressions when they use `await` since there's a lot of magic that happens under the hood with `await` and it means the code is now asynchronous instead of synchronous.  So for readability I don't want to hide it in a nested expression.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +const mockTimeseries = `region,date,cool_metric\n36,2022-08-02,150\n12,2022-08-02,`;
Hrm.  These stringified CSV files are not super readable...  I think you can do multiline strings like:

```
const mockData = 
`region,cool_metric
36,150
12,`;
```

That might be a little better?

I've also seen people do things like:

```
const mockData = [
  'region,cool_metric',
  '36,150', 
  '12,'
].join('\n');
```
I kinda' prefer that, but I think prettier will turn that into a single line which defeats the purpose a bit. :/

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +const mockFetchData = async (
I wouldn't be able to guess what this function does from the name.  I'd maybe:
1. Rename it to "testFetchingCsvData()" or something?
2. Add a brief comment explaining what it does.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +  );
This is very interesting, but I'm not sue I'm a fan. 😆 

As a general rule, I only resort to mocking dependencies (`fetch()` in this case) when absolutely necessary.  Mocking dependencies creates indirect dependencies between the test code and the production code that are not obvious when you are modifying the code.  For example in this case if we ever changed `CsvDataProvider` to use say [axios](https://axios-http.com/docs/intro) to fetch data instead of native `fetch()` then all of our tests will start failing even though we didn't break anything.

Additionally it's generally a bad practice to modify global state, especially from tests.  In this case we are replacing the global `fetch()` function with a fake version but (unless I'm missing it), we are not "putting it back" afterwards so all subsequent tests are going to get a fake version that won't work as normal.

On one last note, I don't think you need the `jest.fn(...)` wrapper here.  I think you use that when you want to track if/when/how a function is called by the code you are testing. But we don't care, so you could just use a plain (unwrapped) lambda function here.

So what would I do instead?  I'd try to change the production code so that it's more easily testable.  In this case, perhaps we should have other ways to pass data into the `CsvDataProvider` other than by URL.  So maybe add a `data` property as an alternative way to specify the CSV contents instead of `url`.  For now we'll only use it in tests, but that's fine.  We can have the comment say "(especially useful for testing)" or something to explain why it's an option.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +  /* URL of the CSV file to import from. */
For these to be doc comments (i.e. "documentation comments") picked up by TypeDoc, they need to start with `/**` not just `/*`

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +  regionColumn: string;
I think we can/should punt for now, but I could imagine letting the caller alternatively pass in a "regionGetter" function that could "calculate" the region ID for any given row using arbitrary logic.  So if you don't have a clean CSV with region IDs already you could have a little lookup function that handles it.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +  url: string;
Per my comment above, perhaps make `url` optional and allow `data` (feel free to come up with a more explicit name) as an alternative way to pass data in.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +    super("csv-data");
I think we want this ID to be configurable (required even) since you may have different CSV sources that you want to refer to for metrics.  E.g. you might have a CSV with region metadata, another CSV with climate data, etc. and you want to create separate data providers and be able to refer to them from metrics.

So I'd change the constructor to `constructor(providerId: string, options: CsvDataProviderOptions)`

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +    const groupedCsvRows = groupBy(csv, (row) => row[this.regionColumn]);
So I'm not sure how much configurability we'll want in terms of caching, but for now I think I would err on the side of aggressive caching which means we might as well only fetch the CSV once.  So I would actually cache the `groupedCsvRows` and use that from `getDataFromCache()`.  Then we can get rid of or move the below code.

I set this up so that fetching / caching could be more granular when it makes sense.  Like if every region's data came from a different file (like with the CAN API), then we would only fetch the files necessary, and cache them.  But in the case of this CSV data provider, might as well cache the whole contents.

We'll probably need to revisit caching behavior in the future, but at this point I'm not sure what we will want.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +          includeTimeseries,
Related to your comment below, if we are respecting `includeTimeseries` when filling the cache, then we probably should include it as part of the cache key.  Although since `populateCache()` just overwrites the cache every time, it probably doesn't matter.  Normally I'd expect it to only populate the cache if it's not already populated.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +    if (!includeTimeseries && metricData.hasTimeseries()) {
Yeah, I think as written the cached entry will always match the args here.

FWIW- You don't really need to check `metricData.hasTimeseries()` before calling `metricData.dropTimeseries()`.  It's safe to just always drop it, even if it's not there.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +          undefined,
nit: Similar to my recommendation on boolean literals, it can make sense for other literals too.  Like here, `/*dateCol=*/undefined`

Basically it's a way to simulate [named arguments](https://en.wikipedia.org/wiki/Named_parameter) (which JavaScript doesn't support 😢) for code readability purposes.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +        .removeNils()
Is this removeNils() necessary / helpful?

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +          "date"
FWIW- All of this repetition (`await mockFetchData(mockTimeseries, /*includeTimeseries=*/ false, "date" )` above and then immediately repeated is another good reason to refactor these tests.  In general the more duplication there are in tests the harder they are to read and to verify that all of the scenarios are being covered.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +  test("dataRowsToMetricData() fails when region data is missing.", async () => {
nit: I had trouble understanding what this meant. Perhaps rephrase to "when there's no data for region."

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +  test("dataRowsToMetricData() succeeds when region data is null.", async () => {
Perhaps rephrase, "when metric data is null"

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +  test("fetchCsv() keeps strings intact", async () => {
I would have had trouble guessing what this test does from the name.  Perhaps "handles CSV values with strings." or something.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +  test("fetchCsv() return null when no cell data is provided", async () => {
This is kinda' misleading.  `fetchCsv()` doesn't return null.  Maybe "fetchCsv() treats missing values as null" or something.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +          metric,
As-is, we are passing `metric` in to `dataRowsToMetricData` and then it is using `metric.id` as if it is the CSV column name, but I think we want more flexibility.  The idea is that I can define a metric with an arbitrary ID (used in the frontend and CMS variables, etc.) and then tie that to an arbitrary column in an arbitrary CSV.  So defining a metric I might do:

```
const metrics = [
  {
    id: "population",
    dataReference: {
      providerId: "region-metadata-csv",
      column: "2020_census_population"
    }
  }];

const dataProviders = [
  new CsvDataProvider('region-metadata-csv', {
    url: '.../region-metadata.csv',
    regionColumn: 'region-id'
  }
]);

const catalog = new MetricCatalog(metrics, dataProviders);
```

or whatever.  I think that probably means we need to pass in a `metricColumn` in addition to `metric` or similar.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +  assert(rows, `No data found for region ${region.regionId}`);
FWIW- I'm not sure if this is the behavior we want, but it's probably better to start out strict and loosen it up if it turns out that's annoying.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +      `Duplicate or no entries for region ${region.regionId} and metric ${metric.id} found.`
I'd probably tweak this to be a bit more helpful diagnostically:

```
`Expected exactly 1 entry for region ${region.regionId} and metric ${metric.id} but found: ${rows.length}`
```

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +      "Entry for metric for region ${region.regionId} and metric ${metric.id} found."
"Entry for metric for region"?  Also should it say "not found"?

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +      [{ date: "2022-08-01", region: "36", another_metric: 100 }],
Am I missing it or do we not have any tests that create a timeseries with more than 1 data point in it?  I feel like that'd be worth testing.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +      : undefined;
I would actually just always have the timeseries be `undefined` since we don't know what date the data is from.

I know this isn't what I did with StaticValueDataProvider, but it's more of a toy data provider and it was handy for testing, etc. to have it provide timeseries data too.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +        "Entry for metric for region ${region.regionId} and metric ${metric.id} found."
"Entry for metric for region" again...

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +function stripTime(date: Date): Date {
I created a `Timeseries.isoDateString()` function that does the same thing (but in a different way).  I wonder if we should just move this logic to the time-utils package.  Feel free to do it as a TODO for now (it would need to happen in multiple PRs anyway).

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +export async function fetchCsv(url: string): Promise<DataRow[]> {
This seems specific to the CsvDataProvider so I would probably move it to that file.

2022-08-16 22:36 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> + * @param rowsDictionary Region-indexed dictionary of data to transform.
Consider renaming to `dataRowsByRegionId` or similar.

2022-08-22 17:40 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +  regionColumn: string;
Yeah, I agree that sounds useful. I think I'll pass on that for now (in this PR) but it does seem like something we'll want

2022-08-22 17:51 UTC, smcclure17 commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +function stripTime(date: Date): Date {
Yeah I think it makes sense to move it--I can tackle that after this gets merged

2022-08-22 17:56 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +          "date"
Yeah good point. I've reworked these tests--I've thinned out a lot of the tests here (in `CsvDataProvider.test.ts`) in favor of doing more testing in `data_uprovider_utils_test.ts`, as `dataRowsToMetricData()` handles a lot of the internal processing used by the CSV provider

2022-08-22 17:57 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +          metric,
Ah, yes that makes a lot of sense! thanks for the explanation + example 🙏

2022-08-22 21:59 UTC, mikelehen approved these changes
Looks good!  Thanks for all the fixes.  I did find some more tweaks to suggest, but feel free to push back / punt if you're not a fan.  They're basically all stylistic / readability stuff, I think.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +  /** Name of column containing valid ISO 8601 date-time values.
nit: If you're doing a `/** ... */` comment and it goes to multiple lines, it's typical to leave the first / last lines blank, so:

```
/** 
 * Name of column containing valid ISO 8601 date-time values.
 * dateColumn must be provided if the CSV contains timeseries data, even if
 * timeseries data will not be used (e.g. by setting includeTimeseries=false) */
 */
```

Also, I find the comment about includeTimeseries=false a bit confusing out-of-context.  I'm not sure if it is necessary / helpful here.  Perhaps something like:

> Name of column containing valid ISO 8601 date-time values. Required if the CSV contains timeseries data, else it should not be specified.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +  const metricColumn = metric.dataReference?.column;
Hrm.  This makes this helper less reusable since it'll basically only work with metrics that use the CsvDataProvider (or other providers that happen to have a `metricColumn` in their data reference), which e.g. probably wouldn't be true for a JSON provider.

So I think it's actually better to explicitly pass in `metricColumn` (or maybe `metricKey`?) as a parameter so that this function doesn't have to make assumptions about the metric.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +  }
nit: This is a highly-debated stylistic thing, but I would wrap the rest of this function in an `} else { ... }` so that the control flow is more explicit.

Basically there's a logical assumption that functions execute until the "end" and you can just look at the return call at the end of a function to see what it returns, and work backwards to understand the logic.  But early returns break that assumption.

The one case where I think early returns aid in readability is when there are trivial edge cases / error conditions that can be handled at the very beginning of the function in order to simplify the rest of the code.  But returning from the middle of a function can make it harder to understand the control flow.  I'd rather an explicit `if { ... return ... } else { ... return ... }` so that it's obvious that there's a branch in the control flow.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +  private cachedData: Dictionary<DataRow[]> = {};
Consider making this a bit more explicit by renaming `cachedData` to `dataRowsByRegionId` and changing the type to ` { [regionId: string]: DataRow[] }`

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +    );
Nice assert!

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +  test("fetchCsv() treats missing values as null", async () => {
This isn't a huge deal, but all else being equal I'd rather that we test our public API (the stuff that consumers of our packages will be seeing / using), which would mean we'd be writing tests against the `CsvDataProvider` instead of against the `fetchCsv()` helper function which is really just an internal implementation detail.

That way:
1. Our tests serve dual-purpose as "example" code and document the contracts of the API (what's expected to work / not) more directly.
2. If we refactor the internals of `CsvDataProvider` in the future and e.g. rework / remove the `fetchCsv()` helper (like I am suggesting to split it into two functions) it wouldn't break any tests.

Not a huge deal, and no need to change it in this PR, but something to consider for the future.  

Sometimes it _does_ make sense to write tests against an internal helper function than against the public API.  E.g. If we intend to use `dataRowsToMetricData()` helper for the JSON provider as well, then writing tests directly against `dataRowsToMetricData()` saves us the effort of writing all those tests twice.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +    const csv = await fetchCsv(this.url, this.csvData);
nit: This is kind of a weird / overloaded function.  It takes two parameters, only one of which is expected to be set, and then it might fetch data from the internet and then it'll parse either the fetched data or the provided data as a CSV.  

I would split it into something like:
```
const csvText = this.fetchCSV();
const csv = parseCsv(csvText);
```

Also maybe rename `csv` to `csvRows` or `rows` or similar since it's no longer comma-separated-values.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +    );
Nit: As a general rule it's nice to avoid iterating over a large body of data multiple times if you can get by with only doing it once.  So I think we could leverage `groupBy`'s behavior to do this more efficiently:

```
const dataRowsByRegionId = groupBy(csv, (row) => row[this.regionColumn]);
assert(!dataRowsByRegionId['undefined'], `One or more CSV rows were missing a region id value in column ${this.regionColumn}`);
```

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +    return metricData.dropTimeseries();
nit: Again I'd put this in an `if { ... } else { ... }`

Also, I'm not sure if this `dropTimeseries()` call is necessary since I think `dataRowsToMetricData()` is respecting the `includeTimeseries` flag already?

That said, it might be simpler to have `dataRowsToMetricData()` _not_ take `includeTimeseries` as a parameter and have it always include the timeseries if you pass `dateColumn`, and then we _would_ want to call `dropTimeseries()` here.  

I don't have a strong preference though.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> + * If both url and csvData are provided data is fetched from the url and csvData is ignored.
As mentioned above, this is kind of a funky description for a funky function.  A good hint that it might be better to split up into multiple functions.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> + * @param dateKey Key name of the items in the data-rows that contain the date-time values.
Perhaps add "To be used when the data-rows represent timeseries data."

That said, I could also see splitting this function into two versions.  One for timeseries data (which requires dateKey) and one for non-timeseries data (which does not take dateKey).  But that'd probably end up with a bit of code duplication between them, so I'm not sure if that's an improvement.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +    return new MetricData(metric, region, value, /**_timeseries=*/ undefined);
nit: `/** ... */` is only for "doc comments" that should be used to generate API docs.  For normal code comments, just `/* ... */`.

That said, because the timeseries is optional, I think you can just omit it. You don't need to explicitly pass `undefined`

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +        `No data for region ${region.regionId} and metric ${metric.id} found.`
This error is kind of confusing.  It's okay if there's not data for a particular region+metric combo, but we expect that to be represented as `null` (I think?).  So what this is really catching is if the metric column is missing entirely.  And chances are if it's missing for one region, then it's missing for all regions (since a CSV has the same columns for every row).

So I think maybe this should be something like: `Metric column ${metricColumn}` missing.`

To be a bit more helpful we could do: `Metric column ${metricColumn} missing for row: ${row}` except unfortunately the default string representation of an array/object is just "[Object object]".  One workaround is to do `JSON.stringify(row)` to get a string representation.  The annoying part is that will generate the string even when the assert succeeds, so it's not ideal from a performance perspective.  Probably not the end of the world, but as a rule we don't want asserts to slow down the code in a meaningful way.  So I'd probably leave it out for now.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +function stripTime(date: Date): Date {
Cool?  Mind actually adding a `// TODO: Merge this logic with Timeseries.isoDateString() and move to time-utils package.` comment?  Then we can do it whenever we get around to it...

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +  );
Again, I think we could avoid iterating the rows twice by moving this assert into the `rows.map(...)` code below.  Basically add a `assert(row[dateKey], ...)` assert similar to the existing `row[metricColumn]` assert.

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +describe("dataRowsToMetricData() without timeseries", () => {
FWIW- This is another hint that this function could be split into two separate ones (one that expects timeseries data, and one that doesn't)

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +describe("fetchCsv()", () => {
fetchCsv() is no longer in data_provider_utils.ts so I think these tests should move?

2022-08-22 21:59 UTC, mikelehen commented on packages/metrics/src/data_providers/CsvDataProvider.test.ts
> +  test("fetchData() fails if timeseries is expected but does not exist in cache.", async () => {
The cache is an implementation detail and I think this test is just cehcking that fetchData() fails if timeseries is expected, but the CSV doesn't provide timeseries data (we didn't provide a `dateColumn`), right?

2022-08-23 14:31 UTC, smcclure17 commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +  }
I see, that makes sense to me--thanks for the context surrounding it. Per the other suggestions, I ended up splitting this into two different functions (one to handle timeseries data and one to handle single datapoints), but I'll keep this in mind for the future! 🙏

2022-08-23 14:32 UTC, smcclure17 commented on packages/metrics/src/data_providers/data_provider_utils.test.ts
> +  test("fetchCsv() treats missing values as null", async () => {
Cool, that sounds good. Good points, and again thanks for the context 🙌

2022-08-23 14:33 UTC, smcclure17 commented on packages/metrics/src/data_providers/CsvDataProvider.ts
> +    return metricData.dropTimeseries();
Yeah, I ended up removing `includeTimeseries` from `dataRowsToMetricData()` and am relying on the `dropTimeseries()` here. Thanks for the suggestion!

2022-08-23 14:34 UTC, smcclure17 commented on packages/metrics/src/data_providers/data_provider_utils.ts
> +function stripTime(date: Date): Date {
ah, yep sorry!

2022-08-23 15:24 UTC, merged