Implement BarChart component
covid-projections/act-now-packages pull request #65
Opened 2022-08-15 20:13 UTC by pnavarrc

2022-08-16 17:49 UTC, mikelehen requested changes
This basically looks good, but I think there may be a slight bug / weakness with calculating the bottom/tops of bars based on the `yScale`.  Though I could also be confused.

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +  /** Scale to transform point dates to pixel positions on the x-axis */
nit: Did we go with d3-scale or similar for LineChart?

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +  /** Scale to transform point values to piel position on the y-axis */
piel => pixel

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> + * corresponding point, make sure to adjust the chart paddings accordingly.
"point, make" => "point. Make" ?

But also I'm not 100% sure what this means.  That I need to have some padding so that the first/last bars don't extend outside the chart bounds?  Maybe make the comment a bit more explicit.

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> + * ```tsx
Oooh, nice.  Didn't know you could specify tsx formatting.

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> + * const yScale = scaleLinear({ domain: [minValue, maxValue], range: [0, height] });
Will this end up with an "upside-down" chart?  Like you'd probably want `[height, 0]` instead?

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> + * consecutive days.
Consider moving this to the `barWidth` documentation on `BarChartProps` so it's closer to where it is used.

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +export interface BarChartOwnProps {
I think we need to export this from the module index.ts too...
```
./packages/ui-components/src/components/BarChart/BarChart.tsx:7:0 - warning BarChartOwnProps is referenced by @actnowcoalition/ui-components.BarChartProps but not included in the documentation.

7    export interface BarChartOwnProps {
```

Right now we're not getting any useful docs for the props:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/206364/184940705-3014f954-f62e-435a-958a-6f2c210c60dd.png">


Same for LineChartOwnProps:

```
./packages/ui-components/src/components/LineChart/LineChart.tsx:8:0 - warning LineChartOwnProps is referenced by @actnowcoalition/ui-components.LineChartProps but not included in the documentation.

8    export interface LineChartOwnProps {
```

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> + * @param barWidth width (in pixels) of each bar.
I'm not sure these `@param` docs are being picked up/used:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/206364/184940893-66c0e549-bafa-40cf-9573-ad41a271734b.png">

I am not sure if there's a way to fix that or if we should just document `BarChartProps` well and rely on that.

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +  return new Date(unixTimeMilliseconds + 1000 * 24 * 60 * 60);
Note that this does not reflect daylight saving time, which may or may not be desired depending on the usage of `nextDay()`.  For this reason I'd slightly prefer not have this `nextDay()` function. Basically as much as possible it would be nice to avoid doing date math and when we have to, centralize it in one package.

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +    barWidth ?? Math.floor(xScale(nextDay(minDate)) - xScale(minDate));
FWIW-  I don't think `minDate` or `nextDay()` are exactly needed here, since we're basically just wanting to get the a bar width corresponding to 1 day (24 hours).  So we could do something like:  `xScale(new Date(24*60*60*1000)) - xScale(new Date(0))`

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +  const [, maxHeight] = yScale.range();
nit: I am not 100% sure what `maxHeight` means.  Would just `height` or `chartHeight` make sense?

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +        const barHeight = yScale(p.value);
Is this assuming that yScale(0) == 0 ?  I think maybe technically this should be `barTop` and we should maybe be calling `yScale(0)` somewhere to get `barBottom` and then using those to draw the bar?  Though FWIW that also assumes that the bars should extend down to "0" in the data coordinate system, which wouldn't work if you had some sort of discontinuous axis (e.g. your y-axis started at 100 instead of 0).  Or am I confused / overthinking this?

I think as-is the code would break if your y range doesn't start at 0, e.g.: 
```
yScale = scaleLinear({
  domain: [minValue, maxValue],
  range: [50, height],
});
```

Though I'm not sure if it ever makes sense to do that.

2022-08-16 17:49 UTC, mikelehen commented on packages/ui-components/src/components/LineChart/LineChart.tsx
> + * const yScale = scaleLinear({ domain: [minVal, maxVal], range: [0, 100] });
Per my comment above, will this end up being an upside-down chart?  You'd want `[100, 0]` ?

2022-08-16 19:12 UTC, pnavarrc commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> + * const yScale = scaleLinear({ domain: [minValue, maxValue], range: [0, height] });
I debated myself a lot over the scale orientation, I think it deserves some standup discussion, I'm going to draw some diagrams to discuss it with the team (also for the bar width offset mentioned above). Thanks for your notes! 🙏

2022-08-16 19:47 UTC, mikelehen commented
FYI- When I check out your branch and run `yarn` I end up with diffs to `yarn.lock`.  You might want to re-run it and add the changes to the PR?

2022-08-22 18:49 UTC, pnavarrc commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +  /** Scale to transform point dates to pixel positions on the x-axis */
That was in the component docs (not the interface), but I think it's better to be more explicit in both the interfaces and component docs, updating LineChart as well 👍

2022-08-22 18:51 UTC, pnavarrc commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> + * corresponding point, make sure to adjust the chart paddings accordingly.
Updated!

2022-08-22 18:52 UTC, pnavarrc commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> + * const yScale = scaleLinear({ domain: [minValue, maxValue], range: [0, height] });
Updated to match LineChart!

2022-08-22 22:45 UTC, mikelehen approved these changes
LGTM though I think there's still technically a bug with the y coordinate calculation, and I'm not 100% sure on the left-aligned vs. center-aligned change.

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.stories.tsx
> +          barWidth={dayWidth - 2}
Any particular reason we use `- 3` above and `- 2` here?

Feels like maybe we should have a `barPadding` constant for consistency / readability. 🤷

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +  /** Timeseries used to draw the line chart */
line => bar

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +  /** d3-scale to transform point values to pixel position on the y-axis */
position => positions

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +   * the distance between 2 consecutive days.
nit: I think the typical convention is that when a `/** ... */` goes to multiple lines, you leave the first / last lines blank, so:

```
/**
 * Width of each bar, in pixels. By default, the barWidth will be set to
 * the distance between 2 consecutive days.
 */
```

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +   * the distance between 2 consecutive days.
Also, it looks like the default is actually `2` now.  I'm curious why you changed it, but in any case we should update the doc comment to match!

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.stories.tsx
> +      <Group left={-0.5 * dayWidth}>
Hrm.  This seems kind of funky.  I guess I'm not 100% sure why we changed it to left-align the bars instead of center-aligning.  Was that in response to my feedback?  I may be missing something.

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +  // timeseries is empty.
I think this is no longer true?

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +            height={maxHeight - rectY}
This doesn't feel right to me.  In theory you should be able to set the yScale range to `[0, innerHeight]` instead of `[innerHeight, 0]` and you'll just end up with an upside-down version of the same chart but instead you get sort of a right-side up chart with "inverted values" (small bars end up big bars and vice versa):

`[innerHeight, 0]`
![image](https://user-images.githubusercontent.com/206364/186030646-dfb15b20-5ef8-4c7e-9c6e-e5a55a395bd0.png)


`[0, innerHeight]`
![image](https://user-images.githubusercontent.com/206364/186030665-6ce164ff-9cfa-416e-a0a7-3e075b1f8706.png)

In theory I think it should be:
```
y={yStart}
height={rectY - yStart}
```

But it looks like SVG doesn't like negative heights so instead you probably need:

```
y={Math.min(yStart, rectY)}
height={Math.abs(rectY - yStart)}
```

And then you correctly get the upside-down chart:
![image](https://user-images.githubusercontent.com/206364/186031204-597237d6-493d-4004-a8df-9d3cd90ad6e5.png)

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/LineChart/LineChart.tsx
> +  /** d3-scale to transform point values to piel position on the y-axis */
nit: position => positions

2022-08-22 22:45 UTC, mikelehen commented on packages/ui-components/src/components/LineChart/LineChart.tsx
> + * const yScale = scaleLinear({ domain: [minVal, maxVal], range: [0, 100] });
ping.  Should this be `[100, 0]` to be a more useful example?

2022-08-23 22:03 UTC, pnavarrc commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +   * the distance between 2 consecutive days.
typo, should be 1!

2022-08-23 22:08 UTC, pnavarrc commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +   * the distance between 2 consecutive days.
I'm leaning towards a simpler default because the parent component will need to be aware and factor in the `barWidth` when defining the scales and to adjust the position of other charting elements, so I set it to be `2px` just so the bars are visible by default. Updating the docs!

2022-08-23 22:15 UTC, pnavarrc commented on packages/ui-components/src/components/BarChart/BarChart.stories.tsx
> +      <Group left={-0.5 * dayWidth}>
After integrating the `LineChart`, I figured that the amount of offset that we want will depend on the context (whether or not the bar chart is composed with other charts or not, etc), so I think it's better and more explicit to leave that concern to the user (since they will be passing the `barWidth` as parameter anyways)

2022-08-23 22:25 UTC, pnavarrc commented on packages/ui-components/src/components/BarChart/BarChart.tsx
> +            height={maxHeight - rectY}
Oh this is much better! 👏 👏 👏

2022-08-23 22:36 UTC, merged