Add time utils
covid-projections/act-now-packages pull request #7
Opened 2022-05-30 22:03 UTC by faihegberg

2022-05-31 18:53 UTC, mikelehen requested changes
Nice!  So this looks 100% fine but given we are turning this into a standalone package I took the opportunity to go over it with a fine-tooth comb and be pretty picky. 😁   I think they should all be quick fixes (mostly comments, etc.) but holler if anything feels onerous or whatever.

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +// Date object constructor takes a zero-indexed month number.
This comment feels a little out of place.  I guess it's not tied to any specific code and it's just a general reminder for somebody trying to understand this code?  That's a good idea, but unless somebody is reading the entire file top to bottom (which is unusual), they're likely to miss the comment when it would be most helpful (e.g. debugging a particular test).

Perhaps consider creating a helper function that hides this oddity of `Date` instead, like:

```
/** 
 * Helper to create Date instances from a numeric year, month, and day.
 *
 * This mostly exists because the Date constructor expects 0-indexed months, 
 * which is pretty unnatural.
 * 
 * The resulting Date will be set to midnight local (Pacific) time.
 * 
 * @param year Numeric year (e.g. 2020)
 * @param month The 1-indexed month (e.g. 3 for March)
 * @param day 1-indexed day (e.g. 25 for the 25th of March).
 * @returns The created Date object.
 */
function createDate(year: number, month: number, day: number) {
  return new Date (year, month-1, day);
}
```

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +describe("time formatting", () => {
nit: These tests are all more about date formatting than time formatting.  So I'd say "date formatting" or "date/time formatting" if we might intend to add time-related tests in the future.

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +    expect(formatDateTime(testDate, DateFormat.MM_DD_YYYY)).toBe("03/01/2020");
This says "Dash separated" but the date is slash-separated?

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +  test("Dash separated date", () => {
Can we put newlines between tests for readability?

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +  });
nit: Is there a particular reason we need specific tests for past dates and future dates?  In general, if a test hits the exact same codepath as other tests, then it's probably redundant and you might consider removing it. 😁 

While it doesn't hurt much to have extra tests, it can become annoying to find the tests you're looking for, or to have extra tests to update if we were to e.g. change the way `formatDateTime` works in the future such that all tests need to be updated.

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +  const testDate = new Date(2020, 2, 1, 20); // March 1st 2020 8 pm. Pacific.
It took me a minute to figure out exactly what's going on with this set of tests.  They look very very similar to the "time formatting" tests above, but they are using `formatUTCDateTime()` instead of `formatDateTime()` and *also* they are using an 8PM (Pacific) time instead of a midnight (Pacific) time.  But why are we changing both the method we call and the Date we call it on?

I think it might be much clearer if we create a single date that is used by both sets of tests (see my comment above).  That way the only thing that changes between the two sets of tests is whether we call `formatDateTime()` vs `formatUTCDateTime()`.

E.g.:

```
/**
 * Test date to use in tests.  Note that our tests are configured in the 
 * package.json to always run in the Pacific timezone, for testing consistency.
 * So this Date represents 2020/03/02 3AM in UTC but 2020/03/01 7PM (or 8PM 
 * depending on daylight savings) in local (Pacific) timezone. So depending which
 * formatting function you use, you'll get back a different date.
 */
const MARCH_2_2020_3AM_UTC = new Date('2020-03-02T03:00:00Z')
```

WDYT?

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +  test("unix time at midnight", () => {
This is really "unix time at 8AM UTC", not midnight, right?

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +      new Date(2020, 2, 1, 0, 0)
nit: This might not be the best test case since hours is `0` already?  So e.g. if we had a bug that treated `TimeUnit.HOURS` as `TimeUnit.DAYS` this test would still pass, I think?

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +// Date object constructor takes a zero-indexed month number.
Oh, I guess we might need hours/minutes as well.

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.ts
> + * Example: parseDateString('2020-03-01') // Return JS date object for March 1st 2020.
Can you follow the example format we've started using in some of the other packages? https://github.com/covid-projections/act-now-packages/blob/4b707346f574c4fd713d97d9e73444f2489ae99f/packages/number-format/src/index.ts#L4

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.ts
> + * Parse date string to JS date object.
nit: By convention there's usually a newline after the initial 1-sentence description of the function.

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.ts
> + */
Feel free to punt for now, but if we wanted to go all-in with tsdoc comments, we could add `@param` and `@returns` descriptions of the params / return value, similar to what we did in number-format and assert. https://github.com/covid-projections/act-now-packages/blob/4b707346f574c4fd713d97d9e73444f2489ae99f/packages/number-format/src/index.ts#L23

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.ts
> + * Subtract a specified amount of time (in units) to date object.
grammar nit: You generally say, "subtract ... from" not "subtract ... to" so this would be "... from date object."

2022-05-31 18:53 UTC, mikelehen commented on packages/time-utils/src/index.ts
> +// Some Luxon functions accept a DurationObject instead of a string as parameter.
I think this comment is explaining why this function exists instead of what it does.  Can you rewrite it as a full tsdoc comment and add a bit more explanation (e.g. "Converts our TimeUnit enum into a luxon Duration object.")?

2022-05-31 18:53 UTC, mikelehen commented on plopfile.mjs
> +yarn add @actnowcoalition/{{dashCase name}}
Hah, woops.  Good catch! 😆

2022-05-31 20:39 UTC, faihegberg commented on packages/time-utils/src/index.test.ts
> +  const testDate = new Date(2020, 2, 1, 20); // March 1st 2020 8 pm. Pacific.
Yep, this definitely makes sense! This would be much clearer 👍🏼

2022-05-31 20:42 UTC, faihegberg commented on packages/time-utils/src/index.test.ts
> +  const testDate = new Date(2020, 2, 1, 20); // March 1st 2020 8 pm. Pacific.
Actually I think I'll just use the same date and time as you suggested for both sets of tests, but I'll create it using the new `createDate` helper function.

2022-06-01 00:05 UTC, faihegberg commented on packages/time-utils/src/index.test.ts
> +  test("unix time at midnight", () => {
Yes!

2022-06-01 00:11 UTC, faihegberg commented on packages/time-utils/src/index.test.ts
> +      new Date(2020, 2, 1, 0, 0)
Changed test case to a non-zero hour instead.

2022-06-01 00:32 UTC, faihegberg commented on packages/time-utils/src/index.ts
> + */
I'll do this in a follow up PR 🙂

2022-06-01 02:39 UTC, mikelehen requested changes
LGTM but I think we accidentally defeated the purpose of some of the `formatDateTime()` / `formatUtcDateTime()` tests.  Mind taking another look?

2022-06-01 02:39 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> + * The resulting Date will be set to midnight local (Pacific) time.
Oh, this doesn't quite apply anymore since we accept hour / minute params.  So I'd remove or tweak it so it still applies.

2022-06-01 02:39 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> + * @param day 1-indexed day (e.g. 25 for the 25th of March).
Can you add `hour` and `minute`?

2022-06-01 02:39 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +  } else return new Date(year, month - 1, day);
Huh. I'm kinda' surprised `prettier` doesn't automatically "fix" this, but I think by convention we almost always wrap if/else blocks in brackets (`{ ... }`).

That said, I think you can maybe just get rid of the if/else logic and do

```
return new Date(year, month - 1, day, hour ?? 0, minute ?? 0);
```

?

2022-06-01 02:39 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> + * depending on daylight savings) in local (Pacific) timezone. So depending which
Oh, I just realized I think I confused myself with the "depending on daylight savings" bit.

Since 3/1 is not during daylight savings time, it'll just always be 12AM I guess.  Sorry!

2022-06-01 02:39 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> + * So this Date represents 2020/03/01 8AM in UTC but 2020/03/01 12AM (or 1AM
I think the date/time you have chosen defeats the purpose of the tests.  I think the original intention was to test that formatDateTime() interprets the Date as local timezone and formatUtcDateTime() interprets the Date as UTC timezone, but because it ends up being 2020/03/01 in both timezones, our tests don't actually verify that `formatDateTime()` and `formatUtcDateTime()` behave differently anymore.

2022-06-01 02:39 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +const MARCH_1_2020_8AM_UTC = createDate(2020, 3, 1, 0, 0);
nit but I think using `createDate()` but then defining the variable name in terms of UTC makes this code harder to read.  I have to do timezone math to understand it, where as ideally code should be "obviously correct" (not require much thought to verify its correctness). So I would stick with either local timezone or UTC timezone and do either:

```
const MARCH_1_2020_8AM_UTC = new Date('2020-03-01T08:00:00Z');
```

or

```
const MARCH_1_2020_12AM_PACIFIC = createDate(2020, 3, 1, 0, 0)
```

Does that make sense?

2022-06-01 02:39 UTC, mikelehen commented on packages/time-utils/src/index.ts
> + * @example: parseDateUnix(1616612130826) // "2021-03-24T18:55:30.826Z"
No `:` after `@example`.  https://tsdoc.org/pages/tags/example/

2022-06-01 02:39 UTC, mikelehen commented on packages/time-utils/src/index.ts
> + * So we must convert a TimeUnit enum to a luxon Duration object first before using these functions.
Very helpful comment, thanks!

2022-06-01 17:08 UTC, pnavarrc commented on packages/time-utils/package.json
> +    "typescript": "^4.6.4"
We need to add `@actnowcoalition/assert` as `dependency` here

2022-06-01 17:16 UTC, pnavarrc commented on package.json
> +    "luxon": "^2.4.0",
The `luxon` library should be a dependency of the `@actnowcoalition/time-utils` package, so it should be in `packages/time-utils/package.json`

2022-06-01 17:18 UTC, pnavarrc commented on packages/time-utils/src/index.ts
> +import { assert } from "@actnowcoalition/assert/src";
This should be `@actnowcoalition/assert`

2022-06-01 18:02 UTC, faihegberg commented on packages/time-utils/src/index.test.ts
> + * The resulting Date will be set to midnight local (Pacific) time.
True!

2022-06-01 18:18 UTC, faihegberg commented on packages/time-utils/src/index.test.ts
> + * So this Date represents 2020/03/01 8AM in UTC but 2020/03/01 12AM (or 1AM
I'll change it to 3.15 am. UTC on March 1st instead so we can more clearly see the difference between `formatDateTime()` and `formatUTCDateTime()`.

2022-06-01 21:11 UTC, mikelehen commented on packages/time-utils/package.json
> +    "typescript": "^4.6.4"
Oh, good catch!  Normally I don't look that closely at this kind of change because I assume if it compiles / runs, then we have all the necessary dependencies.  But I guess that's not necessarily the case here.  Good to know!

2022-06-01 21:12 UTC, mikelehen commented on package.json
> +    "luxon": "^2.4.0",
Same here.  

I do wonder if there is a way we could / should test for this sort of thing so that it gets caught by CI rather than needing to carefully review dependencies. 🤔

2022-06-01 21:12 UTC, mikelehen commented on packages/time-utils/src/index.ts
> +import { assert } from "@actnowcoalition/assert/src";
Another good catch.  I wonder if there's a way to include the source with the package but not make it import-able directly?  Hrm.

2022-06-01 21:23 UTC, mikelehen approved these changes
Couple more optional minor comments from me.  Otherwise LGTM after you fix Pablo's 3 points.

2022-06-01 21:23 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> + * So depending which formatting function you use, you'll get back a different date.
Not a big deal, but why did you decide to include 15 minutes?  It's not really harmful, but I'm also not sure if it's helpful? 😁  I'd generally err towards keeping tests as simple as possible while testing the functionality that you need to test. 🤷

2022-06-01 21:23 UTC, mikelehen commented on packages/time-utils/src/index.test.ts
> +    expect(formatDateTime(testDate, DateFormat.YYYY_MM_DD)).toBe("2020-02-29");
Okay, I may be nitpicking too much, but in order for somebody reading this test to understand why the result is 2020-02-29 they need to know:

1. That our test date is 2020/03/01 3:15 AM UTC and there is an 8 hour time difference between UTC and local (Pacific) time so the local time will represent the date prior to 2020/03/01.
2. That February normally has 28 days.
3. That 2020 was a leap year, and so February had 29 days.

If we picked e.g. `MARCH_2_2020_3_15_AM_UTC` as the test date (March 2 instead of March 1) then a reader of the code wouldn't need to know 2 or 3 and so the test would be more straightforward / easy to understand.

2022-06-01 22:17 UTC, faihegberg commented on packages/time-utils/src/index.test.ts
> + * So depending which formatting function you use, you'll get back a different date.
I added it just in case we add functionalities dealing with minutes in the future, but for now, we don't _need_ it. I'll keep it at the hour.

2022-06-01 22:26 UTC, merged