Add theme colors to Storybook
covid-projections/act-now-packages pull request #80
Opened 2022-08-17 18:27 UTC by pnavarrc

Add theme colors to Storybook.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/114084/185214838-068f4191-752b-46f6-a48f-472076e29069.png">

I just picked up colors automatically from the theme, and excluded `mode` which seems to be an internal MUI thing.

2022-08-18 20:20 UTC, mikelehen requested changes
Hrm.  I'm not sure if this is working for me.   https://act-now-packages--pr80-pablo-colors-to-stor-hp3f4gs8.web.app/storybook/index.html?path=/story/design-system-colors--all is not rendering anything.  Am I confused?

2022-08-18 20:20 UTC, mikelehen commented on packages/ui-components/src/stories/Colors.stories.tsx
> +  .filter((name) => ["mode"].includes(name))
Is this equivalent to `name === 'mode'`? Or am I confused?  If so, then we don't need any of this `Object.keys(...).filter(...)` stuff, right?  We could just basically do `const name = 'mode'` ?  Feel like I may be confused. 😁

2022-08-22 18:18 UTC, pnavarrc commented on packages/ui-components/src/stories/Colors.stories.tsx
> +  .filter((name) => ["mode"].includes(name))
That was a bug 😅  — Some of the palette attributes are functions or non-string constants (such as `getContrastText()` and `contrastThreshold`), so I'm filtering out those. The `mode` attribute is used to name themes (`light`, `dark`), so is also not a color, so I'm filtering it out.

2022-08-22 18:20 UTC, pnavarrc commented on packages/ui-components/src/stories/Colors.stories.tsx
> +  .filter((name) => ["mode"].includes(name))
Adding a comment to explain that 👍

2022-08-22 22:04 UTC, mikelehen approved these changes
Looks good!

2022-08-22 22:04 UTC, mikelehen commented on packages/ui-components/src/stories/Colors.stories.tsx
> +// so we filter that out as well.
Very helpful comment, thanks!

2022-08-22 22:41 UTC, merged